name: "Dep Jobs Example"

on: push

jobs:
  runs-on: ubuntu-latest
  job2:
    needs: job1
    steps:
      - name: stepA
        run: echo "World"
  job1:
    steps:
      - name: stepB
        run: echo "Hello"
